### ISSUE TITLE
Unable to authenticate using the compiled app. 

### ISSUE THREAD

**Issue by froyomuffin** [ChunxiaZhang/Toaster#11]
Compile and get the app to work. Either on actual device or in android emulator. Currently, there's an authentication issue.

**Comment by froyomuffin** [comment]
Just needed to register the fork to OAuth at https://github.com/settings/applications/new

Then, PocketHub can be made aware of our App's clientID and client secret via:
GITHUB_CLIENT=your_application_client_id
GITHUB_SECRET=your_application_client_secret
GITHUB_CALLBACK=your_callback_url

The callback_url should match the same callback scheme set when registering the app on github

Full details at:
https://developer.github.com/v3/oauth/

**Comment by froyomuffin** [comment]
Re-opened. I think I'm using the callback wrong. It's just opening github mobile in the app.

**Comment by ChunxiaZhang** [comment]
I got the same problem!!

**Comment by froyomuffin** [comment]
Got it. 
So the callback url must be set (on both github and in github.properties) to
    pockethub://

That's it. This value is read by app/gradle.build and will automatically update the @string scheme resource in AndroidManifest.xml during build.

**Comment by froyomuffin** [comment]
Reopen for tracking
